### ISSUE TITLE
Child process doesn't bubble up exceptions

### ISSUE THREAD

**Issue by GordonDiggs** [barracudanetworks/forkdaemon-php#26]
I don't see any way to bubble up exceptions raised by child processes. Is there a callback or anything that I'm missing?

Take this code:

```php
$server = new fork_daemon();
$server->max_children_set(5);
$server->max_work_per_child_set(3);
$server->register_child_run("process_child_run");
$server->register_logging("logger", fork_daemon::LOG_LEVEL_ALL);

run();

function run()
{
  global $server;

  $server->addwork(array("work"));
  $server->process_work(true);

  echo("Done!\n");
}

function process_child_run($data_set, $identifier = "")
{
  echo("I am a child, I'll last a while\n");
  throw new Exception("cry");
}
```

I would expect the error to be raised and not see the `Done!`, but I get this output:

```console
/code $ php run.php 
I am a child, I'll last a while
PHP Fatal error:  Uncaught exception 'Exception' with message 'cry' in /code/run.php:26
Stack trace:
#0 [internal function]: process_child_run(Array)
#1 /code/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1851): call_user_func_array('process_child_r...', Array)
#2 /code/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1771): fork_daemon->invoke_callback('process_child_r...', Array, false)
#3 /code/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1673): fork_daemon->fork_work_unit(Array, '', -1)
#4 /code/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1423): fork_daemon->process_work_unit(-1)
#5 /code/run.php(18): fork_daemon->process_work(true)
#6 /code/run.php(11): run()
#7 {main}
  thrown in /code/run.php on line 26
Done!
```

**Comment by mrrsm** [comment]
>I would expect the error to be raised and not see the Done!, but I get this output:

The exception is happening in a separate process as your function `process_child_run` is being forked off.  Your parent process has no problem continuing because all it knows is the child it forked off has finished and the parent can continue on.

I have not tested to see how registering a callback for the results work but this example may be closer to what you are hoping to see. [Callback Example](https://github.com/barracudanetworks/forkdaemon-php/blob/master/examples/result_callback.php)  Even then I don't think the exception will bubble to the parent but you could send an error code response back to the parent and handle that as a thrown exception in the parent process.

**Comment by GordonDiggs** [comment]
@mrrsm the callback never gets executed because no results are returned. I notice that the `child_exit` function is called, but contains no information about the exitcode for the child. Is there a way to get that information in there?

Updated code and output:

```php
$server = new fork_daemon();
$server->max_children_set(5);
$server->max_work_per_child_set(3);
$server->register_child_run("process_child_run");
$server->register_parent_child_exit("process_child_exit");
$server->register_logging("logger", fork_daemon::LOG_LEVEL_ALL);
$server->register_parent_results("process_results");

run();

function run()
{
  global $server;

	$server->addwork(array("work"));
  $server->process_work(true);

  echo("Done!\n");
}

function process_child_run($data_set, $identifier = "")
{
  echo("I am a child, I'll last a while\n");
  throw new Exception("cry");

  return "child done";
}

function process_results($results, $identifier = "")
{
	echo "Results: " . implode(",", $results) . "\n";
}

function process_child_exit($pid, $identifier = "")
{
	echo "Child $pid just finished" . "\n";
}
```

```console
/code $ php run.php 
I am a child, I'll last a while
PHP Fatal error:  Uncaught exception 'Exception' with message 'cry' in /code/run.php:28
Stack trace:
#0 [internal function]: process_child_run(Array)
#1 /code/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1851): call_user_func_array('process_child_r...', Array)
#2 /code/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1771): fork_daemon->invoke_callback('process_child_r...', Array, false)
#3 /code/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1673): fork_daemon->fork_work_unit(Array, '', -1)
#4 /code/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1423): fork_daemon->process_work_unit(-1)
#5 /code/run.php(20): fork_daemon->process_work(true)
#6 /code/run.php(13): run()
#7 {main}
  thrown in /code/run.php on line 28
Child 24 just finished
Done!
```

**Comment by mrrsm** [comment]
I am pretty sure the exception here will prevent your return statement from running.
```php
function process_child_run($data_set, $identifier = "")
{
  echo("I am a child, I'll last a while\n");
  throw new Exception("cry");

  return "child done";
}
```

If we change this to allow the forked function to handle the exception and then pass data back to the parent we should be able to handle it.  Heck you may be able to just serialize the exception that is handed back and then just unserialize it in the parent callback and check if is an exception or some other structure you are hoping for.
```php
function process_child_run($data_set, $identifier = "")
{
  $return = 0;
  try {
    echo("I am a child, I'll last a while\n");
    throw new Exception("cry");
  } catch (\Exception $e) {
    $return = $e->getMessage();
    // Or you could check codes if you are setting them
    // $return = $e->getCode();
  }

  return $return;
}
```

**Comment by GordonDiggs** [comment]
@mrrsm Yep caching and returning worked - thanks! For posterity: here's how the code ended up (matching some of the things we're doing in our library):

```php
$server = new fork_daemon();
$server->store_result_set(true);
$server->max_children_set(5);
$server->max_work_per_child_set(3);
$server->register_child_run("process_child_run");
$server->register_parent_child_exit("process_child_exit");
$server->register_logging("logger", fork_daemon::LOG_LEVEL_ALL);

run();

function run()
{
  global $server;

	$server->addwork(array("work"));
  $server->process_work(true);

  foreach ($server->get_all_results() as $result) {
    if ($result == "error") {
      error_log("something threw an exception!\n");
    } else {
      echo("result: $result\n");
    }
  }
}

function process_child_run($data_set, $identifier = "")
{
  try {
    echo("I am a child, I'll last a while\n");
    throw new Exception("cry");

    return "child done";
  } catch (Exception $e) {
    error_log("Exception: " . $e->getMessage() . " in " . $e->getFile() . "\n" . $e->getTraceAsString());
    return "error";
  }
}

function process_child_exit($pid, $identifier = "")
{
	echo "Child $pid just finished" . "\n";
}
```
